"""update packageUser relationship

Revision ID: f8c2ff2e4d55
Revises: 6615a0e26a90
Create Date: 2021-10-12 15:23:33.765966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c2ff2e4d55'
down_revision = '6615a0e26a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'package', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'package', type_='foreignkey')
    op.drop_column('package', 'user_id')
    # ### end Alembic commands ###
